environment: "production"

loadFixtures: false

image:
  repository: hello-world-from-db
  pullPolicy: Never # minikube usecase
  tag: latest

imagePullSecrets: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

redis:
  cluster:
    enabled: true
    slaveCount: 1
  existingSecret: db-credentials
  existingSecretPasswordKey: dbPassword
  usePasswordFile: true

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod-hello-world-from-db.local
      paths:
        - path: /
          backend:
            serviceName: hello-world-from-db-dev
            servicePort: 80
  tls:
    - secretName: prod-hello-world-from-db-tls
      hosts:
        - prod-hello-world-from-db.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}
